# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descripton',
            new_name='description',
        ),
    ]
