# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160406_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsolved',
            name='response_based_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questionsolved',
            name='time_based_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
